/**
 * Notification Edit Page
 * Route: /notifications/[id]/edit
 * Based on R11 rules
 * 
 * NOTE: Notifications cannot be edited. They are auto-generated by the scheduler.
 * This route redirects to the notification detail page (which then redirects to document).
 * 
 * Access Rules:
 * - Member (Owner): Can access their own notifications
 * - FamilyAdmin: Can access all family notifications
 */

"use client";

import { useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import { RouteGuard } from "@/core/guards/route-guard";
import { UserRole } from "@/modules/f001-identity/types/responses/auth";
import { notificationRoutes } from "@/utils/routing";

export default function NotificationEditPage() {
  const router = useRouter();
  const params = useParams();
  const notificationId = params?.id as string | undefined;

  useEffect(() => {
    // Redirect to notification detail (which redirects to document)
    if (notificationId) {
      router.replace(notificationRoutes.detail(notificationId));
    } else {
      // If no ID, redirect to list
      router.replace(notificationRoutes.list);
    }
  }, [router, notificationId]);

  return (
    <RouteGuard
      requireAuth={true}
      roles={[UserRole.Member, UserRole.FamilyAdmin]}
    >
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-center">
          <div className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-primary-600 border-r-transparent"></div>
          <p className="mt-4 text-gray-600">Redirecting...</p>
        </div>
      </div>
    </RouteGuard>
  );
}

