/**
 * Notification Create Page
 * Route: /notifications/create
 * Based on R11 rules
 * 
 * NOTE: Notifications are auto-generated by the scheduler, not created via UI.
 * This route redirects to the notification list page.
 * 
 * Access Rules:
 * - Member (Owner): Can access
 * - FamilyAdmin: Can access
 */

"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { RouteGuard } from "@/core/guards/route-guard";
import { UserRole } from "@/modules/f001-identity/types/responses/auth";
import { notificationRoutes } from "@/utils/routing";

export default function NotificationCreatePage() {
  const router = useRouter();

  useEffect(() => {
    // Redirect to notification list since notifications are auto-generated
    router.replace(notificationRoutes.list);
  }, [router]);

  return (
    <RouteGuard
      requireAuth={true}
      roles={[UserRole.Member, UserRole.FamilyAdmin]}
    >
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-center">
          <div className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-primary-600 border-r-transparent"></div>
          <p className="mt-4 text-gray-600">Redirecting...</p>
        </div>
      </div>
    </RouteGuard>
  );
}

