/**
 * Notification Request Types
 * Based on API Spec: F05_api_spec.md
 * Domain Model: F05_domain_model.md
 * UI Data Contract: F05_ui_data_contract.md
 * 
 * NOTE: Notifications are created automatically by the scheduler (not via API).
 * Create and Update operations are defined here for type consistency with R2 rules,
 * but they are NOT currently supported by the API.
 * PATCH operations (mark as read) have no request body.
 */

/**
 * Notification Base Interface
 * Represents the base structure of a Notification entity
 * 
 * NOTE: Notifications are not created via API - they are generated by the scheduler.
 * This interface is defined for type consistency with R2 rules.
 */
export interface NotificationBase {
  id: string; // UUID format (RFC 4122 UUID v4)
  document_id: string; // UUID format (RFC 4122 UUID v4)
  reminder_type: "30d" | "7d" | "0d"; // Reminder type enum
  is_read: boolean; // Read/unread state
  created_at: string; // ISO 8601 format, UTC timezone (Z suffix required)
  updated_at: string; // ISO 8601 format, UTC timezone (Z suffix required)
}

/**
 * Notification Create Request
 * POST /v1/notifications (NOT CURRENTLY SUPPORTED - Notifications created by scheduler)
 * 
 * NOTE: This operation does not exist in the current API.
 * Notifications are automatically created by the daily scheduler at 00:00 UTC.
 * Defined for type consistency with R2 rules.
 */
export interface NotificationCreate {
  // Notifications are not created via API
  // This interface is empty as notifications are generated by the scheduler
}

/**
 * Notification Update Request
 * PATCH /v1/notifications/{notification_id} (NOT CURRENTLY SUPPORTED)
 * 
 * NOTE: The API only supports PATCH /v1/notifications/{notification_id}/read
 * which has no request body. This interface is defined for type consistency with R2 rules.
 */
export interface NotificationUpdate {
  // Notifications are not updated via API (only marked as read, which has no body)
  // This interface is empty
}

/**
 * Notification List Parameters
 * GET /v1/notifications
 * 
 * Query parameters for listing notifications with pagination and sorting.
 * Returns only notifications for the current authenticated user (Owner or FamilyAdmin).
 */
export interface NotificationListParams {
  page?: number; // Page number (≥ 1), default: 1
  page_size?: number; // Page size (1-100), default: 20
  sort_by?: string; // Sort field: "created_at" (only allowed value), default: "created_at"
  sort_order?: "asc" | "desc"; // Sort order, default: "desc"
}

/**
 * Notification Mark as Read Request
 * PATCH /v1/notifications/{notification_id}/read
 * 
 * Request body for marking a notification as read.
 * The notification_id is provided as a path parameter.
 */
export interface NotificationMarkReadRequest {
  is_read: boolean; // Set to true to mark notification as read
}

/**
 * Notification Mark All as Read Request
 * PATCH /v1/notifications/read-all
 * 
 * Request body for marking all notifications as read.
 */
export interface NotificationMarkAllReadRequest {
  is_read: boolean; // Set to true to mark all notifications as read
}

